# Shared Apache virtual-host configuration for MediaWiki HTTP and HTTPS.
ServerAdmin webmaster@localhost
DocumentRoot /var/www/html

CustomLog "| /usr/bin/rotatelogs -p /usr/bin/pruneaccesslogs ${APACHE_LOG_DIR}/access.%Y-%m-%d-%H-%M-%S.log 256M" logfmt
CustomLog /dev/stdout logfmt
AllowEncodedSlashes NoDecode
