name: Documentation (Read the Docs)

on:
  pull_request:
  merge_group:

jobs:
  rtd-docs-checks:
    uses: canonical/operator-workflows/.github/workflows/docs_rtd.yaml@main
    secrets: inherit
    with:
      python-version: 3.11
